name: Mandy Formula CI
on: [push]
env:
  HOMEBREW_NO_AUTO_UPDATE: 1
jobs:
  test-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
          
      - name: "Test Formula on Ubuntu."
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y build-essential procps curl file git gcc
          git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew
          mkdir -p ~/.linuxbrew/bin
          ln -s ~/.linuxbrew/Homebrew/bin/brew ~/.linuxbrew/bin/brew
          eval "$(~/.linuxbrew/bin/brew shellenv)"
          export HOMEBREW_NO_AUTO_UPDATE=1
          brew config
          brew --version
          brew install --formula $(pwd)/Formula/mandy.rb
          $(brew --prefix mandy)/bin/mandy --version
          
      - name: "Install the Formula."
        if: runner.os == 'Macos'
        run: |
          brew install --formula $(pwd)/Formula/mandy.rb
          echo $(uname -m)
          mandy --version
